DROP TABLE IF EXISTS JC_CONTACT;
 
CREATE TABLE JC_CONTACT
(
        CONTACT_ID SERIAL,
        FIRST_NAME VARCHAR(50) NOT NULL,
        LAST_NAME VARCHAR(50) NOT NULL,
        PHONE VARCHAR(50) NOT NULL,
        EMAIL VARCHAR(50) NOT NULL,
        PRIMARY KEY (CONTACT_ID)
);
 
INSERT INTO JC_CONTACT (FIRST_NAME, LAST_NAME, PHONE, EMAIL) VALUES ('Peter','Belgy','+79112345678','peter@pisem.net');
INSERT INTO JC_CONTACT (FIRST_NAME, LAST_NAME, PHONE, EMAIL) VALUES ('Helga','Forte','+79118765432','helga@pisem.net');
 
SELECT * from JC_CONTACT;